# Generated by Django 3.2.9 on 2021-11-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inscripción'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='sector_lab',
            field=models.CharField(choices=[('CA', 'Trabajador por Cuenta Ajena'), ('EA', 'Empresario/Autónomo'), ('SE', 'Sector Educativo'), ('FP', 'Funcionario Público'), ('E', 'Emprendedor'), ('O', 'ONG'), ('D', 'Desempleado'), ('ES', 'Estudiante'), ('OL', 'Otra')], default='', max_length=2, verbose_name='Situación Laboral'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
