# Generated by Django 3.2.9 on 2021-11-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_auto_20211109_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='educativo_sector',
            field=models.CharField(choices=[('', ''), ('UN', 'Universitario'), ('BA', 'Bachillerato'), ('ES', 'ESO'), ('FP', 'FP'), ('CF', 'Ciclos Formativos'), ('PI', 'Primaria Infantil')], default='', max_length=2, verbose_name='Sector Educativo'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estudiante_especialidad',
            field=models.CharField(blank=True, max_length=150, verbose_name='Estudiante Especialidad'),
        ),
    ]
