# Generated by Django 3.2.9 on 2021-11-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_auto_20211109_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='sector_lab',
            new_name='sector_laboral',
        ),
    ]
