# Generated by Django 3.2.9 on 2021-11-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0004_rename_sector_lab_inscripcion_sector_laboral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='competencias_clave_eleccion',
            field=models.TextField(verbose_name='¿Puedes decirnos, de las 10 competencias clave mencionadas en este documento, cuáles priorizarías para desarrollar más y aplicarlas en tu vida?'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='desplegar_aprendido',
            field=models.TextField(verbose_name='¿Cómo desplegarías lo aprendido?'),
        ),
    ]
