# Generated by Django 3.2.9 on 2021-11-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0005_auto_20211109_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='proximo_anio',
            field=models.TextField(verbose_name='Qué estás dispuesto hacer el próximo año con todo lo aprendido en el marco de la Sociedad del Aprendizaje?'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='proyectos',
            field=models.TextField(verbose_name='Tienes idea o proyectos para desarrollar o implementar en tu vida?'),
        ),
    ]
