# Generated by Django 3.2.9 on 2021-11-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0007_inscripcion_emprendedor_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='dni',
            field=models.CharField(max_length=12, unique=True, verbose_name='DNI'),
        ),
    ]
