# Generated by Django 3.2.9 on 2021-11-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0009_alter_inscripcion_sector_laboral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='mujer',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='varon',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='sexo',
            field=models.CharField(choices=[('V', 'Varón'), ('M', 'Mujer')], default='M', max_length=1, verbose_name='Sexo'),
        ),
    ]
