# Generated by Django 3.2.9 on 2021-11-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0010_auto_20211115_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_inscripcion_comunidad_lsa',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inscripción en la Comunidad LSA'),
        ),
    ]
