# Generated by Django 3.2.9 on 2021-11-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0011_inscripcion_fecha_inscripcion_comunidad_lsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='en_plazo',
            field=models.BooleanField(default=False, verbose_name='En plazo'),
        ),
    ]
