# Generated by Django 3.2.9 on 2021-11-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0014_alter_inscripcion_estado_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='primer_taller',
            field=models.CharField(choices=[('A', 'Taller de Formación de 10:00 a 14:00 el lunes 17 de enero 2022 en Mérida.'), ('B', 'Taller de Formación de 16:30 a 20:30 el martes 18 de enero 2022 en Mérida.'), ('C', 'Taller de Formación de 10:00 a 14:00 el miércoles 19 de enero 2022 en Mérida.'), ('D', 'Taller de Formación de 16:30 a 20:30 el jueves 20 de enero 2022 en Mérida.')], default='A', max_length=1, verbose_name='Primer Taller'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='segundo_taller',
            field=models.CharField(choices=[('A', 'Taller de Formación de 10:00 a 14:00 el lunes 23 de mayo de 2022 en Mérida.'), ('B', 'Taller de Formación de 16:30 a 20:30 el martes 24 de mayo de 2022 en Mérida.'), ('C', 'Taller de Formación de 10:00 a 14:00 el miércoles 25 de mayo de 2022 en Mérida.'), ('D', 'Taller de Formación de 16:30 a 20:30 el jueves 26 de mayo de 2022 en Mérida.')], default='B', max_length=1, verbose_name='Segundo Taller'),
        ),
    ]
