# Generated by Django 3.2.9 on 2021-11-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0015_auto_20211129_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='dni',
            field=models.CharField(blank=True, max_length=12, verbose_name='DNI'),
        ),
    ]
