# Generated by Django 3.2.9 on 2021-12-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0016_alter_inscripcion_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='compromiso',
            field=models.CharField(blank=True, max_length=300, verbose_name='Compromiso'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='conoce_eslogan_congreso_tres_detalle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Eslogan 3er Congreso'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='emprendedor_sector',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sector Emprendedor'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='empresario_sector',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sector Empresario Autónomo'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estudiante_especialidad',
            field=models.CharField(blank=True, max_length=300, verbose_name='Estudiante Especialidad'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='funcionario_sector',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sector Funcionario'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='ong_sector',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sector ONG'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='otro_area_laboral',
            field=models.CharField(blank=True, max_length=300, verbose_name='Otro Sector'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='trabajador_cuenta_ajena_sector',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sector Cuenta Ajena'),
        ),
    ]
