# Generated by Django 3.2.8 on 2021-10-28 07:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0002_alter_plantilla_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='body_content',
            field=tinymce.models.HTMLField(verbose_name='Contenido'),
        ),
    ]
