# Generated by Django 3.2.8 on 2021-11-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0003_alter_plantilla_body_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='identificador',
            field=models.SlugField(default='rename-me', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
